image: docker:18.09
services:
  - docker:18.09-dind
  


variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login --username oauth --password ${TOKEN} cr.yandex
    - docker build --build-arg CI_BUILD_TAG="$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID" -t cr.yandex/${REGISTRY}/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID .
    - docker push cr.yandex/${REGISTRY}/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID

deploy:
  image: exzotikfruit/kubectl:1.16-debian-10
  stage: deploy
  script:
    - echo ${KUBE} | base64 -d > kube.config
    - echo ${CA} | base64 -d > ca.pem
    - export KUBECONFIG=kube.config
    - sed -i "s/__VERSION__/$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID/" deployment.yaml
    - sed -i "s/__REGISTRY__/${REGISTRY}/" deployment.yaml
    - sed -i "s/__PROJECT__/${CI_PROJECT_NAME}/" deployment.yaml
    - kubectl apply -f deployment.yamlA